// src/pages/Index.vue
<template>
  <div class="min-h-screen w-full overflow-x-hidden">
    <Header />
    <HeroVideo />
    <AboutUsSection />
    <TeamSection />
    <YearCardsSection />
    <QBanksSection />
    <FeaturesSection />
    <ContactSection />
    <Footer />
  </div>
</template>

<script setup lang="ts">
import Header from "@/components/Header.vue";
import HeroVideo from "@/components/HeroVideo.vue";
import AboutUsSection from "@/components/AboutUsSection.vue";
import TeamSection from "@/components/TeamSection.vue";
import YearCardsSection from "@/components/YearCardsSection.vue";
import QBanksSection from "@/components/QBanksSection.vue";
import FeaturesSection from "@/components/FeaturesSection.vue";
import ContactSection from "@/components/ContactSection.vue";
import Footer from "@/components/Footer.vue";
</script>

// src/pages/Index.tsx
import Header from "@/components/Header";
import HeroVideo from "@/components/HeroVideo";
import AboutUsSection from "@/components/AboutUsSection";
import TeamSection from "@/components/TeamSection";
import YearCardsSection from "@/components/YearCardsSection";
import QBanksSection from "@/components/QBanksSection";
import FeaturesSection from "@/components/FeaturesSection";
import ContactSection from "@/components/ContactSection";
import Footer from "@/components/Footer";

const Index = () => {
  return (
    <div className="min-h-screen w-full overflow-x-hidden">
      <Header />
      <HeroVideo />
      <AboutUsSection />
      <TeamSection />
      <YearCardsSection />
      <QBanksSection />
      <FeaturesSection />
      <ContactSection />
      <Footer />
    </div>
  );
};

export default Index;
