// src/pages/YearPage.tsx
import YearPageHeader from "@/components/YearPageHeader";
import YearHero from "@/components/YearHero";
import CoursesSection from "@/components/CoursesSection";
import UniversitiesSection from "@/components/UniversitiesSection";
import ContactSection from "@/components/ContactSection";
import Footer from "@/components/Footer";

const YearPage = () => {
  return (
    <div className="min-h-screen">
      <YearPageHeader />
      <YearHero />
      <CoursesSection />
      <UniversitiesSection />
      <ContactSection />
      <Footer />
    </div>
  );
};

export default YearPage;

// src/pages/YearPage.vue
<template>
  <div class="min-h-screen">
    <YearPageHeader />
    <YearHero />
    <CoursesSection />
    <UniversitiesSection />
    <ContactSection />
    <Footer />
  </div>
</template>

<script setup lang="ts">
import YearPageHeader from "@/components/YearPageHeader.vue";
import YearHero from "@/components/YearHero.vue";
import CoursesSection from "@/components/CoursesSection.vue";
import UniversitiesSection from "@/components/UniversitiesSection.vue";
import ContactSection from "@/components/ContactSection.vue";
import Footer from "@/components/Footer.vue";
</script>
