// src/components/UniversitiesSection.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MapPin, Users, BookOpen, Award } from "lucide-react";

const universities = [
  {
    id: 1,
    name: "Harvard Medical School",
    location: "Boston, MA",
    students: "10K+",
    programs: "25+",
    ranking: "#1",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Harvard_University_coat_of_arms.svg/240px-Harvard_University_coat_of_arms.svg.png",
    description: "Leading medical education institution with cutting-edge research facilities"
  },
  {
    id: 2,
    name: "Johns Hopkins School of Medicine",
    location: "Baltimore, MD",
    students: "8.5K+",
    programs: "22+",
    ranking: "#2",
    image: "/lovable-uploads/7bfbfef7-3da9-447c-80c5-b6b4691b8917.png",
    description: "Renowned for innovative medical research and clinical excellence"
  },
  {
    id: 3,
    name: "Stanford Medicine",
    location: "Stanford, CA",
    students: "7.2K+",
    programs: "20+",
    ranking: "#3",
    image: "/lovable-uploads/540413e5-ab8a-41ea-815e-0c2ea9f5d421.png",
    description: "Pioneer in translational medicine and biomedical innovation"
  },
  {
    id: 4,
    name: "Mayo Clinic College of Medicine",
    location: "Rochester, MN",
    students: "6.8K+",
    programs: "18+",
    ranking: "#4",
    image: "/lovable-uploads/7fee58d2-510d-45f7-9b20-fa94ba74047b.png",
    description: "Excellence in patient care education and medical training"
  }
];

const UniversitiesSection = () => {
  return (
    <section id="universities" className="py-20 bg-secondary/10">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
            Partner Universities
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            We collaborate with top-tier medical institutions worldwide to provide the best educational experience
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {universities.map((university) => (
            <Card key={university.id} className="group hover:shadow-xl transition-all duration-300 hover:scale-105 border-border bg-card relative overflow-hidden h-full flex flex-col">
              <div className="absolute top-4 left-4 bg-primary text-primary-foreground px-3 py-1 rounded-full text-sm font-bold z-10">
                {university.ranking}
              </div>
              
              <div className="relative overflow-hidden">
                <img 
                  src={university.image} 
                  alt={university.name}
                  className="w-full h-40 object-cover group-hover:scale-110 transition-transform duration-300"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-background/80 to-transparent" />
              </div>
              
              <CardHeader className="pb-2">
                <CardTitle className="text-lg font-bold line-clamp-2">{university.name}</CardTitle>
                <div className="flex items-center gap-1 text-muted-foreground text-sm">
                  <MapPin className="w-4 h-4" />
                  {university.location}
                </div>
              </CardHeader>
              
              <CardContent className="pt-2 flex-grow flex flex-col">
                <p className="text-sm text-muted-foreground mb-4 line-clamp-2">
                  {university.description}
                </p>
                
                <div className="grid grid-cols-3 gap-2 text-center mb-4">
                  <div className="flex flex-col items-center">
                    <Users className="w-4 h-4 text-primary mb-1" />
                    <span className="text-xs font-semibold">{university.students}</span>
                    <span className="text-xs text-muted-foreground">Students</span>
                  </div>
                  <div className="flex flex-col items-center">
                    <BookOpen className="w-4 h-4 text-primary mb-1" />
                    <span className="text-xs font-semibold">{university.programs}</span>
                    <span className="text-xs text-muted-foreground">Programs</span>
                  </div>
                  <div className="flex flex-col items-center">
                    <Award className="w-4 h-4 text-primary mb-1" />
                    <span className="text-xs font-semibold">Top</span>
                    <span className="text-xs text-muted-foreground">Ranked</span>
                  </div>
                </div>
                
                <button className="w-full mt-auto bg-primary hover:bg-primary/90 text-primary-foreground py-2 rounded-lg font-semibold transition-colors text-sm">
                  Learn More
                </button>
              </CardContent>
            </Card>
          ))}
        </div>
        
        <div className="text-center mt-16">
          <a href="/universities">
            <button className="bg-secondary hover:bg-secondary/90 text-secondary-foreground px-8 py-3 rounded-lg font-semibold transition-all duration-300 hover:scale-105">
              View All Universities
            </button>
          </a>
        </div>
      </div>
    </section>
  );
};

export default UniversitiesSection;

// src/components/UniversitiesSection.vue
<template>
  <section id="universities" class="py-20 bg-secondary/10">
    <div class="container mx-auto px-4">
      <div class="text-center mb-16">
        <h2 class="text-3xl md:text-4xl font-bold mb-4 bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
          Partner Universities
        </h2>
        <p class="text-lg text-muted-foreground max-w-2xl mx-auto">
          We collaborate with top-tier medical institutions worldwide to provide the best educational experience
        </p>
      </div>
      
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        <div 
          v-for="university in universities" 
          :key="university.id"
          class="group hover:shadow-xl transition-all duration-300 hover:scale-105 border-border bg-card relative overflow-hidden h-full flex flex-col rounded-lg"
        >
          <div class="absolute top-4 left-4 bg-primary text-primary-foreground px-3 py-1 rounded-full text-sm font-bold z-10">
            {{ university.ranking }}
          </div>
          
          <div class="relative overflow-hidden">
            <img 
              :src="university.image" 
              :alt="university.name"
              class="w-full h-40 object-cover group-hover:scale-110 transition-transform duration-300"
            />
            <div class="absolute inset-0 bg-gradient-to-t from-background/80 to-transparent" />
          </div>
          
          <div class="p-6 pb-2 flex-grow flex flex-col">
            <h3 class="text-lg font-bold mb-2 line-clamp-2">{{ university.name }}</h3>
            <div class="flex items-center gap-1 text-muted-foreground text-sm mb-4">
              <MapPin class="w-4 h-4" />
              {{ university.location }}
            </div>
            
            <p class="text-sm text-muted-foreground mb-4 line-clamp-2">
              {{ university.description }}
            </p>
            
            <div class="grid grid-cols-3 gap-2 text-center mb-4">
              <div class="flex flex-col items-center">
                <Users class="w-4 h-4 text-primary mb-1" />
                <span class="text-xs font-semibold">{{ university.students }}</span>
                <span class="text-xs text-muted-foreground">Students</span>
              </div>
              <div class="flex flex-col items-center">
                <BookOpen class="w-4 h-4 text-primary mb-1" />
                <span class="text-xs font-semibold">{{ university.programs }}</span>
                <span class="text-xs text-muted-foreground">Programs</span>
              </div>
              <div class="flex flex-col items-center">
                <Award class="w-4 h-4 text-primary mb-1" />
                <span class="text-xs font-semibold">Top</span>
                <span class="text-xs text-muted-foreground">Ranked</span>
              </div>
            </div>
            
            <button class="w-full mt-auto bg-primary hover:bg-primary/90 text-primary-foreground py-2 rounded-lg font-semibold transition-colors text-sm">
              Learn More
            </button>
          </div>
        </div>
      </div>
      
      <div class="text-center mt-16">
        <a href="/universities">
          <button class="bg-secondary hover:bg-secondary/90 text-secondary-foreground px-8 py-3 rounded-lg font-semibold transition-all duration-300 hover:scale-105">
            View All Universities
          </button>
        </a>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { MapPin, Users, BookOpen, Award } from 'lucide-vue-next';

const universities = [
  {
    id: 1,
    name: "Harvard Medical School",
    location: "Boston, MA",
    students: "10K+",
    programs: "25+",
    ranking: "#1",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Harvard_University_coat_of_arms.svg/240px-Harvard_University_coat_of_arms.svg.png",
    description: "Leading medical education institution with cutting-edge research facilities"
  },
  {
    id: 2,
    name: "Johns Hopkins School of Medicine",
    location: "Baltimore, MD",
    students: "8.5K+",
    programs: "22+",
    ranking: "#2",
    image: "/lovable-uploads/7bfbfef7-3da9-447c-80c5-b6b4691b8917.png",
    description: "Renowned for innovative medical research and clinical excellence"
  },
  {
    id: 3,
    name: "Stanford Medicine",
    location: "Stanford, CA",
    students: "7.2K+",
    programs: "20+",
    ranking: "#3",
    image: "/lovable-uploads/540413e5-ab8a-41ea-815e-0c2ea9f5d421.png",
    description: "Pioneer in translational medicine and biomedical innovation"
  },
  {
    id: 4,
    name: "Mayo Clinic College of Medicine",
    location: "Rochester, MN",
    students: "6.8K+",
    programs: "18+",
    ranking: "#4",
    image: "/lovable-uploads/7fee58d2-510d-45f7-9b20-fa94ba74047b.png",
    description: "Excellence in patient care education and medical training"
  }
];
</script>
